name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up SSH key
        run: |
          echo "$PA_TOKEN" > key.pem
          chmod 600 key.pem

      - name: Deploy to PythonAnywhere
        uses: appleboy/scp-action@master
        with:
          host: ohrafaelmartins.ssh.pythonanywhere.com
          username: ohrafaelmartins
          key: ${{ env.SSH_PRIVATE_KEY }}
          source: ./
          target: /home/ohrafaelmartins/
        env:
          SSH_PRIVATE_KEY: |
            ${{ secrets.PA_TOKEN }}